library(dplyr)  #Load library for functions to clean data

#Loading the dataframe from a csv generated by a C++ program
primes<-read.csv("/home/jatin/Documents/Classes/Spring_2018/PHY110C/Final_proj/PHY110C_FinalProject/Raw_Data.csv", header = TRUE)

freq <- primes %>% count(n_even)  #selecting distinct even numbers and the number of combinations of primes
diff_tab <- primes %>% mutate(diff=q-p) %>% group_by(n_even) %>% summarise(avg=mean(diff))  #finding the avg difference between p and q for every even number
p_freq <- primes %>% count(p) %>% arrange(p_order=desc(n))
q_freq <- primes %>% count(q) %>% arrange(q_order=desc(n))

common <- p_freq %>% left_join(q_freq, by = c("p"="q")) %>% mutate(appear=n.x+n.y) %>% arrange(desc(appear)) %>% select(p, appear)

#Writing the dataframes as csv files
write.csv(freq, file = "/home/jatin/Documents/Classes/Spring_2018/PHY110C/Final_proj/Graph1.csv")
write.csv(common, file = "/home/jatin/Documents/Classes/Spring_2018/PHY110C/Final_proj/Graph2.csv")
write.csv(diff_tab, file = "/home/jatin/Documents/Classes/Spring_2018/PHY110C/Final_proj/Graph3.csv")